const mysql = require('mysql2/promise');
const config = require('../config');

const TABLES_SQL = `
CREATE TABLE IF NOT EXISTS \`user\` (
  \`id\` BIGINT UNSIGNED NOT NULL AUTO_INCREMENT COMMENT '主键ID',
  \`openid\` VARCHAR(64) NOT NULL DEFAULT '' COMMENT '微信openid',
  \`session_key\` VARCHAR(64) NOT NULL DEFAULT '' COMMENT '微信session_key',
  \`phone\` VARCHAR(20) NOT NULL DEFAULT '' COMMENT '手机号',
  \`nickname\` VARCHAR(64) NOT NULL DEFAULT '口算小达人' COMMENT '用户昵称',
  \`avatar_url\` VARCHAR(500) NOT NULL DEFAULT '' COMMENT '头像地址',
  \`grade\` VARCHAR(10) NOT NULL DEFAULT '1-up' COMMENT '年级：1-up-一年级上 1-down-一年级下 2-up-二年级上 2-down-二年级下',
  \`total_stars\` INT UNSIGNED NOT NULL DEFAULT 0 COMMENT '星星总数',
  \`level\` TINYINT UNSIGNED NOT NULL DEFAULT 1 COMMENT '等级：1-5',
  \`streak_days\` INT UNSIGNED NOT NULL DEFAULT 0 COMMENT '当前连续打卡天数',
  \`max_streak_days\` INT UNSIGNED NOT NULL DEFAULT 0 COMMENT '历史最长连续打卡天数',
  \`create_time\` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
  \`update_time\` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间',
  PRIMARY KEY (\`id\`),
  UNIQUE KEY \`uk_openid\` (\`openid\`),
  KEY \`idx_phone\` (\`phone\`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci COMMENT='用户表';

CREATE TABLE IF NOT EXISTS \`practice_record\` (
  \`id\` BIGINT UNSIGNED NOT NULL AUTO_INCREMENT COMMENT '主键ID',
  \`openid\` VARCHAR(64) NOT NULL DEFAULT '' COMMENT '用户openid',
  \`type\` VARCHAR(20) NOT NULL DEFAULT '' COMMENT '练习类型：oral_calc-口算 reading-读题',
  \`practice_date\` DATE NOT NULL COMMENT '练习日期',
  \`total_count\` SMALLINT UNSIGNED NOT NULL DEFAULT 0 COMMENT '总题数',
  \`correct_count\` SMALLINT UNSIGNED NOT NULL DEFAULT 0 COMMENT '正确题数',
  \`duration_seconds\` INT UNSIGNED NOT NULL DEFAULT 0 COMMENT '总用时（秒）',
  \`stars_earned\` SMALLINT UNSIGNED NOT NULL DEFAULT 0 COMMENT '本次获得星星数',
  \`detail\` JSON DEFAULT NULL COMMENT '每题明细JSON',
  \`create_time\` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
  PRIMARY KEY (\`id\`),
  KEY \`idx_openid_date\` (\`openid\`, \`practice_date\`),
  KEY \`idx_openid_type\` (\`openid\`, \`type\`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci COMMENT='练习记录表';

CREATE TABLE IF NOT EXISTS \`oral_calc_error\` (
  \`id\` BIGINT UNSIGNED NOT NULL AUTO_INCREMENT COMMENT '主键ID',
  \`openid\` VARCHAR(64) NOT NULL DEFAULT '' COMMENT '用户openid',
  \`expression\` VARCHAR(30) NOT NULL DEFAULT '' COMMENT '算式，如 7+5',
  \`correct_answer\` INT NOT NULL DEFAULT 0 COMMENT '正确答案',
  \`user_answer\` INT NOT NULL DEFAULT 0 COMMENT '用户答案',
  \`op_type\` VARCHAR(10) NOT NULL DEFAULT '' COMMENT '运算类型：add-加法 sub-减法 mul-乘法 div-除法',
  \`reviewed\` TINYINT UNSIGNED NOT NULL DEFAULT 0 COMMENT '是否已订正：0-未订正 1-已订正',
  \`error_count\` SMALLINT UNSIGNED NOT NULL DEFAULT 1 COMMENT '该题累计错误次数',
  \`create_time\` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
  \`reviewed_at\` DATETIME DEFAULT NULL COMMENT '订正时间',
  PRIMARY KEY (\`id\`),
  KEY \`idx_openid_reviewed\` (\`openid\`, \`reviewed\`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci COMMENT='口算错题表';

CREATE TABLE IF NOT EXISTS \`reading_question\` (
  \`id\` BIGINT UNSIGNED NOT NULL AUTO_INCREMENT COMMENT '主键ID',
  \`grade\` VARCHAR(10) NOT NULL DEFAULT '' COMMENT '适用年级：1-up-一年级上 1-down-一年级下 2-up-二年级上 2-down-二年级下',
  \`difficulty\` TINYINT UNSIGNED NOT NULL DEFAULT 1 COMMENT '难度：1-简单 2-中等 3-困难',
  \`content\` TEXT NOT NULL COMMENT '题目正文',
  \`math_infos\` JSON NOT NULL COMMENT '数学信息列表JSON',
  \`math_question\` VARCHAR(200) NOT NULL DEFAULT '' COMMENT '数学问题',
  \`distractors\` JSON NOT NULL COMMENT '信息干扰项列表JSON（用于第一步找数学信息）',
  \`question_distractors\` JSON NOT NULL COMMENT '问题干扰项列表JSON（用于第二步找数学问题）',
  \`answer\` INT DEFAULT NULL COMMENT '参考答案（数值）',
  \`audio_url\` VARCHAR(500) NOT NULL DEFAULT '' COMMENT 'TTS音频地址',
  \`status\` TINYINT UNSIGNED NOT NULL DEFAULT 1 COMMENT '状态：0-下线 1-上线',
  \`create_time\` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
  PRIMARY KEY (\`id\`),
  KEY \`idx_grade_status\` (\`grade\`, \`status\`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci COMMENT='读题题库表';

CREATE TABLE IF NOT EXISTS \`reading_error\` (
  \`id\` BIGINT UNSIGNED NOT NULL AUTO_INCREMENT COMMENT '主键ID',
  \`openid\` VARCHAR(64) NOT NULL DEFAULT '' COMMENT '用户openid',
  \`question_id\` BIGINT UNSIGNED NOT NULL DEFAULT 0 COMMENT '题目ID',
  \`error_type\` VARCHAR(20) NOT NULL DEFAULT '' COMMENT '错误类型：miss_info-漏选信息 extra_info-多选干扰 wrong_question-问题选错',
  \`user_infos\` JSON DEFAULT NULL COMMENT '用户选择的数学信息JSON',
  \`user_question\` VARCHAR(200) NOT NULL DEFAULT '' COMMENT '用户选择的数学问题',
  \`reviewed\` TINYINT UNSIGNED NOT NULL DEFAULT 0 COMMENT '是否已订正：0-未订正 1-已订正',
  \`create_time\` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
  PRIMARY KEY (\`id\`),
  KEY \`idx_openid\` (\`openid\`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci COMMENT='读题错题表';

CREATE TABLE IF NOT EXISTS \`checkin\` (
  \`id\` BIGINT UNSIGNED NOT NULL AUTO_INCREMENT COMMENT '主键ID',
  \`openid\` VARCHAR(64) NOT NULL DEFAULT '' COMMENT '用户openid',
  \`checkin_date\` DATE NOT NULL COMMENT '打卡日期',
  \`oral_calc_done\` TINYINT UNSIGNED NOT NULL DEFAULT 0 COMMENT '口算是否完成：0-未完成 1-已完成',
  \`reading_done\` TINYINT UNSIGNED NOT NULL DEFAULT 0 COMMENT '读题是否完成：0-未完成 1-已完成',
  \`all_done\` TINYINT UNSIGNED NOT NULL DEFAULT 0 COMMENT '当日任务是否全部完成：0-未完成 1-已完成',
  \`create_time\` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
  \`update_time\` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间',
  PRIMARY KEY (\`id\`),
  UNIQUE KEY \`uk_openid_date\` (\`openid\`, \`checkin_date\`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci COMMENT='打卡记录表';
`;

const SEED_QUESTIONS = [
  // ========== 一年级上册（14道）==========
  {
    grade: '1-up', difficulty: 1,
    content: '小明有8个苹果，妈妈给了他2个橙子。小明吃了3个苹果。小明还剩多少个苹果？',
    math_infos: ['小明有8个苹果', '吃了3个苹果'],
    math_question: '小明还剩多少个苹果',
    distractors: ['妈妈给了他2个橙子'],
    question_distractors: ['妈妈给了几个橙子', '小明一共有多少个水果'],
    answer: 5,
  },
  {
    grade: '1-up', difficulty: 1,
    content: '树上有5只小鸟，树下有2只小猫在晒太阳。又飞来了4只小鸟。树上现在有多少只小鸟？',
    math_infos: ['树上有5只小鸟', '又飞来了4只小鸟'],
    math_question: '树上现在有多少只小鸟',
    distractors: ['树下有2只小猫在晒太阳'],
    question_distractors: ['树下有几只小猫', '一共有多少只动物'],
    answer: 9,
  },
  {
    grade: '1-up', difficulty: 1,
    content: '妈妈买了6个橘子和3个梨。爸爸买了1瓶牛奶。妈妈一共买了多少个水果？',
    math_infos: ['买了6个橘子', '买了3个梨'],
    math_question: '妈妈一共买了多少个水果',
    distractors: ['爸爸买了1瓶牛奶'],
    question_distractors: ['爸爸买了几瓶牛奶', '一共花了多少钱'],
    answer: 9,
  },
  {
    grade: '1-up', difficulty: 1,
    content: '教室里有12个小朋友，隔壁教室有15个小朋友在画画。走了4个小朋友。教室里还有多少个小朋友？',
    math_infos: ['教室里有12个小朋友', '走了4个'],
    math_question: '教室里还有多少个小朋友',
    distractors: ['隔壁教室有15个小朋友在画画'],
    question_distractors: ['隔壁教室有几个小朋友', '两间教室一共有多少个小朋友'],
    answer: 8,
  },
  {
    grade: '1-up', difficulty: 1,
    content: '小红有7颗糖，小华有3颗糖。小明给了小红5颗糖。小红现在有多少颗糖？',
    math_infos: ['小红有7颗糖', '小明给了小红5颗糖'],
    math_question: '小红现在有多少颗糖',
    distractors: ['小华有3颗糖'],
    question_distractors: ['小华有几颗糖', '三个人一共有多少颗糖'],
    answer: 12,
  },
  {
    grade: '1-up', difficulty: 1,
    content: '鱼缸里有6条金鱼，鱼缸旁边有1只小猫在看。妈妈又买了3条金鱼。鱼缸里现在有多少条金鱼？',
    math_infos: ['鱼缸里有6条金鱼', '又买了3条金鱼'],
    math_question: '鱼缸里现在有多少条金鱼',
    distractors: ['鱼缸旁边有1只小猫在看'],
    question_distractors: ['旁边有几只小猫', '一共有多少只动物'],
    answer: 9,
  },
  {
    grade: '1-up', difficulty: 1,
    content: '盘子里有10个饺子，碗里有4个汤圆。弟弟吃了4个饺子。盘子里还剩多少个饺子？',
    math_infos: ['盘子里有10个饺子', '弟弟吃了4个饺子'],
    math_question: '盘子里还剩多少个饺子',
    distractors: ['碗里有4个汤圆'],
    question_distractors: ['碗里有几个汤圆', '一共有多少个食物'],
    answer: 6,
  },
  {
    grade: '1-up', difficulty: 1,
    content: '小明有9块积木，小华有6块拼图。小红有4块积木。小明和小红一共有多少块积木？',
    math_infos: ['小明有9块积木', '小红有4块积木'],
    math_question: '小明和小红一共有多少块积木',
    distractors: ['小华有6块拼图'],
    question_distractors: ['小华有几块拼图', '三个人一共有多少个玩具'],
    answer: 13,
  },
  {
    grade: '1-up', difficulty: 1,
    content: '公交车上有11个人，站台上有3个人在等车。到站下去了5个人。车上还有多少个人？',
    math_infos: ['公交车上有11个人', '下去了5个人'],
    math_question: '车上还有多少个人',
    distractors: ['站台上有3个人在等车'],
    question_distractors: ['站台上有几个人', '车上和站台一共有多少人'],
    answer: 6,
  },
  {
    grade: '1-up', difficulty: 1,
    content: '笔筒里有3支铅笔和4支彩笔。书包里有2本书。笔筒里一共有多少支笔？',
    math_infos: ['有3支铅笔', '有4支彩笔'],
    math_question: '笔筒里一共有多少支笔',
    distractors: ['书包里有2本书'],
    question_distractors: ['书包里有几本书', '铅笔比彩笔少几支'],
    answer: 7,
  },
  {
    grade: '1-up', difficulty: 1,
    content: '草地上有8只蝴蝶，花丛里有4只蜜蜂在采蜜。飞走了2只蝴蝶。草地上还有多少只蝴蝶？',
    math_infos: ['草地上有8只蝴蝶', '飞走了2只蝴蝶'],
    math_question: '草地上还有多少只蝴蝶',
    distractors: ['花丛里有4只蜜蜂在采蜜'],
    question_distractors: ['花丛里有几只蜜蜂', '一共有多少只昆虫'],
    answer: 6,
  },
  {
    grade: '1-up', difficulty: 1,
    content: '小兔子拔了7个萝卜，小鹿采了5个蘑菇。小兔子又拔了6个萝卜。小兔子一共拔了多少个萝卜？',
    math_infos: ['拔了7个萝卜', '又拔了6个萝卜'],
    math_question: '小兔子一共拔了多少个萝卜',
    distractors: ['小鹿采了5个蘑菇'],
    question_distractors: ['小鹿采了几个蘑菇', '一共采了多少个食物'],
    answer: 13,
  },
  {
    grade: '1-up', difficulty: 1,
    content: '桌上有5个红杯子和7个蓝杯子。柜子里还有3个绿杯子。桌上一共有多少个杯子？',
    math_infos: ['有5个红杯子', '有7个蓝杯子'],
    math_question: '桌上一共有多少个杯子',
    distractors: ['柜子里还有3个绿杯子'],
    question_distractors: ['柜子里有几个杯子', '红蓝绿杯子一共有多少个'],
    answer: 12,
  },
  {
    grade: '1-up', difficulty: 1,
    content: '姐姐有14颗珠子，妈妈有20颗珠子。姐姐给了妹妹6颗珠子。姐姐还有多少颗珠子？',
    math_infos: ['姐姐有14颗珠子', '给了妹妹6颗珠子'],
    math_question: '姐姐还有多少颗珠子',
    distractors: ['妈妈有20颗珠子'],
    question_distractors: ['妈妈有几颗珠子', '妹妹现在有几颗珠子'],
    answer: 8,
  },

  // ========== 一年级下册（12道）==========
  {
    grade: '1-down', difficulty: 1,
    content: '停车场有15辆车，门口停了2辆自行车。开走了8辆车。停车场还剩多少辆车？',
    math_infos: ['停车场有15辆车', '开走了8辆车'],
    math_question: '停车场还剩多少辆车',
    distractors: ['门口停了2辆自行车'],
    question_distractors: ['门口有几辆自行车', '一共有多少辆车和自行车'],
    answer: 7,
  },
  {
    grade: '1-down', difficulty: 1,
    content: '小明看一本故事书，这本书一共有30页。第一天看了9页，第二天看了7页。两天一共看了多少页？',
    math_infos: ['第一天看了9页', '第二天看了7页'],
    math_question: '两天一共看了多少页',
    distractors: ['这本书一共有30页'],
    question_distractors: ['这本书一共有几页', '还剩多少页没有看'],
    answer: 16,
  },
  {
    grade: '1-down', difficulty: 2,
    content: '花园里有18朵红花和9朵黄花，还有7朵白花。摘了5朵红花。花园里还有多少朵红花？',
    math_infos: ['花园里有18朵红花', '摘了5朵红花'],
    math_question: '花园里还有多少朵红花',
    distractors: ['有9朵黄花', '还有7朵白花'],
    question_distractors: ['花园里有几朵黄花', '花园里一共有多少朵花'],
    answer: 13,
  },
  {
    grade: '1-down', difficulty: 1,
    content: '小明有16张贴纸，小华有10张贴纸。小明送给同学9张贴纸。小明还剩多少张贴纸？',
    math_infos: ['小明有16张贴纸', '送给同学9张贴纸'],
    math_question: '小明还剩多少张贴纸',
    distractors: ['小华有10张贴纸'],
    question_distractors: ['小华有几张贴纸', '小明比小华多几张贴纸'],
    answer: 7,
  },
  {
    grade: '1-down', difficulty: 1,
    content: '池塘里有8只青蛙，岸上有3只乌龟在晒太阳。又跳来了6只青蛙。池塘里现在有多少只青蛙？',
    math_infos: ['池塘里有8只青蛙', '又跳来了6只青蛙'],
    math_question: '池塘里现在有多少只青蛙',
    distractors: ['岸上有3只乌龟在晒太阳'],
    question_distractors: ['岸上有几只乌龟', '一共有多少只动物'],
    answer: 14,
  },
  {
    grade: '1-down', difficulty: 1,
    content: '商店里有17个玩具，仓库里有12个玩具。卖出了8个玩具。商店里还剩多少个玩具？',
    math_infos: ['商店里有17个玩具', '卖出了8个玩具'],
    math_question: '商店里还剩多少个玩具',
    distractors: ['仓库里有12个玩具'],
    question_distractors: ['仓库里有几个玩具', '一共有多少个玩具'],
    answer: 9,
  },
  {
    grade: '1-down', difficulty: 2,
    content: '小明摘了12个桃子，小红摘了8个桃子。树上还有10个桃子没摘。他们一共吃了5个桃子。还剩多少个桃子？',
    math_infos: ['小明摘了12个桃子', '小红摘了8个桃子', '吃了5个桃子'],
    math_question: '还剩多少个桃子',
    distractors: ['树上还有10个桃子没摘'],
    question_distractors: ['树上还有几个桃子', '小明和小红一共摘了多少个'],
    answer: 15,
  },
  {
    grade: '1-down', difficulty: 1,
    content: '妈妈买了14个鸡蛋，还买了3个鸭蛋。做饭用了6个鸡蛋。还剩多少个鸡蛋？',
    math_infos: ['买了14个鸡蛋', '用了6个鸡蛋'],
    math_question: '还剩多少个鸡蛋',
    distractors: ['还买了3个鸭蛋'],
    question_distractors: ['买了几个鸭蛋', '一共买了多少个蛋'],
    answer: 8,
  },
  {
    grade: '1-down', difficulty: 1,
    content: '小丽有5朵红花和9朵黄花。小明有3朵蓝花。小丽一共有多少朵花？',
    math_infos: ['有5朵红花', '有9朵黄花'],
    math_question: '小丽一共有多少朵花',
    distractors: ['小明有3朵蓝花'],
    question_distractors: ['小明有几朵花', '他们一共有多少朵花'],
    answer: 14,
  },
  {
    grade: '1-down', difficulty: 2,
    content: '图书角有20本书，旁边还有5本杂志。借走了7本书，又还回来3本书。图书角现在有多少本书？',
    math_infos: ['图书角有20本书', '借走了7本书', '还回来3本书'],
    math_question: '图书角现在有多少本书',
    distractors: ['旁边还有5本杂志'],
    question_distractors: ['旁边有几本杂志', '一共借出去了多少本'],
    answer: 16,
  },
  {
    grade: '1-down', difficulty: 1,
    content: '爷爷养了11只鸡，奶奶养了8只鸭。爷爷又买了5只鸡。爷爷现在有多少只鸡？',
    math_infos: ['爷爷养了11只鸡', '又买了5只鸡'],
    math_question: '爷爷现在有多少只鸡',
    distractors: ['奶奶养了8只鸭'],
    question_distractors: ['奶奶养了几只鸭', '一共有多少只家禽'],
    answer: 16,
  },
  {
    grade: '1-down', difficulty: 1,
    content: '小强跳绳跳了13下，小丽跳了8下。小明跳了10下。小强比小丽多跳了多少下？',
    math_infos: ['小强跳了13下', '小丽跳了8下'],
    math_question: '小强比小丽多跳了多少下',
    distractors: ['小明跳了10下'],
    question_distractors: ['小明跳了几下', '三个人一共跳了多少下'],
    answer: 5,
  },

  // ========== 二年级上册（13道）==========
  {
    grade: '2-up', difficulty: 1,
    content: '书架上有35本书，桌上还有10本杂志。小明又放了28本书到书架上。书架上现在有多少本书？',
    math_infos: ['书架上有35本书', '又放了28本书'],
    math_question: '书架上现在有多少本书',
    distractors: ['桌上还有10本杂志'],
    question_distractors: ['桌上有几本杂志', '书和杂志一共有多少本'],
    answer: 63,
  },
  {
    grade: '2-up', difficulty: 2,
    content: '学校买了6盒铅笔，每盒有8支。还买了3盒橡皮。学校一共买了多少支铅笔？',
    math_infos: ['买了6盒铅笔', '每盒有8支'],
    math_question: '学校一共买了多少支铅笔',
    distractors: ['还买了3盒橡皮'],
    question_distractors: ['买了几盒橡皮', '铅笔和橡皮一共买了多少盒'],
    answer: 48,
  },
  {
    grade: '2-up', difficulty: 2,
    content: '操场上有45个同学在做操，教室里还有20个同学在读书。走了18个同学，又来了7个。操场上现在有多少个同学？',
    math_infos: ['操场上有45个同学', '走了18个', '又来了7个'],
    math_question: '操场上现在有多少个同学',
    distractors: ['教室里还有20个同学在读书'],
    question_distractors: ['教室里有几个同学', '学校一共有多少个同学'],
    answer: 34,
  },
  {
    grade: '2-up', difficulty: 1,
    content: '果园里有47棵苹果树和36棵梨树。山上还有15棵桃树。果园里一共有多少棵果树？',
    math_infos: ['有47棵苹果树', '有36棵梨树'],
    math_question: '果园里一共有多少棵果树',
    distractors: ['山上还有15棵桃树'],
    question_distractors: ['山上有几棵桃树', '苹果树比梨树多几棵'],
    answer: 83,
  },
  {
    grade: '2-up', difficulty: 1,
    content: '小明有75元，小红有50元。小明买书花了38元。小明还剩多少元？',
    math_infos: ['小明有75元', '买书花了38元'],
    math_question: '小明还剩多少元',
    distractors: ['小红有50元'],
    question_distractors: ['小红有多少元', '小明比小红多几元'],
    answer: 37,
  },
  {
    grade: '2-up', difficulty: 2,
    content: '教室里有4排桌子，每排有7张。每张桌子上放了2把椅子。教室里一共有多少张桌子？',
    math_infos: ['有4排桌子', '每排有7张'],
    math_question: '教室里一共有多少张桌子',
    distractors: ['每张桌子上放了2把椅子'],
    question_distractors: ['一共有多少把椅子', '桌子和椅子一共有多少'],
    answer: 28,
  },
  {
    grade: '2-up', difficulty: 2,
    content: '小红买了3包饼干，每包有9块。她还买了2瓶牛奶。小红一共买了多少块饼干？',
    math_infos: ['买了3包饼干', '每包有9块'],
    math_question: '小红一共买了多少块饼干',
    distractors: ['她还买了2瓶牛奶'],
    question_distractors: ['买了几瓶牛奶', '一共花了多少钱'],
    answer: 27,
  },
  {
    grade: '2-up', difficulty: 1,
    content: '学校有82个足球，还有30个篮球。借出去了45个足球。学校还剩多少个足球？',
    math_infos: ['学校有82个足球', '借出去了45个足球'],
    math_question: '学校还剩多少个足球',
    distractors: ['还有30个篮球'],
    question_distractors: ['学校有几个篮球', '足球和篮球一共有多少个'],
    answer: 37,
  },
  {
    grade: '2-up', difficulty: 2,
    content: '妈妈买了5袋牛奶，每袋有6瓶。爸爸喝了2瓶果汁。家里已经有3瓶牛奶。家里现在一共有多少瓶牛奶？',
    math_infos: ['买了5袋牛奶', '每袋有6瓶', '家里已经有3瓶'],
    math_question: '家里现在一共有多少瓶牛奶',
    distractors: ['爸爸喝了2瓶果汁'],
    question_distractors: ['爸爸喝了几瓶果汁', '一共买了多少瓶饮料'],
    answer: 33,
  },
  {
    grade: '2-up', difficulty: 1,
    content: '小华看了一本书，这本书一共有120页。上午看了24页，下午看了38页。一天看了多少页？',
    math_infos: ['上午看了24页', '下午看了38页'],
    math_question: '一天看了多少页',
    distractors: ['这本书一共有120页'],
    question_distractors: ['这本书有几页', '还剩多少页没看'],
    answer: 62,
  },
  {
    grade: '2-up', difficulty: 2,
    content: '同学们去植树，一年级种了28棵，二年级种了35棵。三年级种了42棵，去年一共种了50棵。一年级和二年级一共种了多少棵？',
    math_infos: ['一年级种了28棵', '二年级种了35棵'],
    math_question: '一年级和二年级一共种了多少棵',
    distractors: ['三年级种了42棵', '去年一共种了50棵'],
    question_distractors: ['三年级种了几棵', '三个年级一共种了多少棵'],
    answer: 63,
  },
  {
    grade: '2-up', difficulty: 1,
    content: '小明做了26道数学题，小红做了37道数学题。小华做了30道语文题。他们一共做了多少道数学题？',
    math_infos: ['小明做了26道数学题', '小红做了37道数学题'],
    math_question: '他们一共做了多少道数学题',
    distractors: ['小华做了30道语文题'],
    question_distractors: ['小华做了几道语文题', '三个人一共做了多少道题'],
    answer: 63,
  },
  {
    grade: '2-up', difficulty: 2,
    content: '动物园有9只猴子，旁边有5只孔雀。每只猴子吃了3个香蕉。猴子们一共吃了多少个香蕉？',
    math_infos: ['有9只猴子', '每只吃了3个香蕉'],
    math_question: '一共吃了多少个香蕉',
    distractors: ['旁边有5只孔雀'],
    question_distractors: ['有几只孔雀', '一共有多少只动物'],
    answer: 27,
  },

  // ========== 二年级下册（15道）==========
  {
    grade: '2-down', difficulty: 1,
    content: '有56个苹果，还有3个橘子。平均分给7个小朋友。每个小朋友分到多少个苹果？',
    math_infos: ['有56个苹果', '平均分给7个小朋友'],
    math_question: '每个小朋友分到多少个苹果',
    distractors: ['还有3个橘子'],
    question_distractors: ['有几个橘子', '一共有多少个水果'],
    answer: 8,
  },
  {
    grade: '2-down', difficulty: 2,
    content: '一本书有86页，旁边还有一本50页的漫画书。小华第一天看了34页，第二天看了28页。还剩多少页没有看？',
    math_infos: ['一本书有86页', '第一天看了34页', '第二天看了28页'],
    math_question: '还剩多少页没有看',
    distractors: ['旁边还有一本50页的漫画书'],
    question_distractors: ['漫画书有几页', '两天一共看了多少页'],
    answer: 24,
  },
  {
    grade: '2-down', difficulty: 1,
    content: '有36块糖，还有12块巧克力。平均分给4个小朋友。每个小朋友分到多少块糖？',
    math_infos: ['有36块糖', '平均分给4个小朋友'],
    math_question: '每个小朋友分到多少块糖',
    distractors: ['还有12块巧克力'],
    question_distractors: ['有几块巧克力', '糖和巧克力一共有多少'],
    answer: 9,
  },
  {
    grade: '2-down', difficulty: 1,
    content: '一条绳子长72厘米，另一条绳子长50厘米。剪去了35厘米。还剩多少厘米？',
    math_infos: ['绳子长72厘米', '剪去了35厘米'],
    math_question: '还剩多少厘米',
    distractors: ['另一条绳子长50厘米'],
    question_distractors: ['另一条绳子有多长', '两条绳子一共有多长'],
    answer: 37,
  },
  {
    grade: '2-down', difficulty: 2,
    content: '学校买了8盒粉笔，每盒有9支。上个月买了5盒粉笔。用了15支。还剩多少支粉笔？',
    math_infos: ['买了8盒粉笔', '每盒有9支', '用了15支'],
    math_question: '还剩多少支粉笔',
    distractors: ['上个月买了5盒粉笔'],
    question_distractors: ['上个月买了几盒', '一共买了多少支粉笔'],
    answer: 57,
  },
  {
    grade: '2-down', difficulty: 1,
    content: '有45个气球，每组有8个小朋友。平均分给5组小朋友。每组分到多少个气球？',
    math_infos: ['有45个气球', '平均分给5组'],
    math_question: '每组分到多少个气球',
    distractors: ['每组有8个小朋友'],
    question_distractors: ['每组有几个小朋友', '一共有多少个小朋友'],
    answer: 9,
  },
  {
    grade: '2-down', difficulty: 2,
    content: '小明看一本90页的故事书，小红看一本60页的漫画书。第一天看了32页，第二天看了29页。还剩多少页没看？',
    math_infos: ['故事书有90页', '第一天看了32页', '第二天看了29页'],
    math_question: '还剩多少页没看',
    distractors: ['小红看一本60页的漫画书'],
    question_distractors: ['小红的漫画书有几页', '两天一共看了多少页'],
    answer: 29,
  },
  {
    grade: '2-down', difficulty: 1,
    content: '花店有63朵玫瑰，还有40朵百合。卖出了28朵玫瑰。花店还剩多少朵玫瑰？',
    math_infos: ['花店有63朵玫瑰', '卖出了28朵玫瑰'],
    math_question: '花店还剩多少朵玫瑰',
    distractors: ['还有40朵百合'],
    question_distractors: ['花店有几朵百合', '花店一共有多少朵花'],
    answer: 35,
  },
  {
    grade: '2-down', difficulty: 2,
    content: '超市运来7箱牛奶，每箱有8瓶。昨天卖掉了10瓶牛奶。超市一共运来多少瓶牛奶？',
    math_infos: ['运来7箱牛奶', '每箱有8瓶'],
    math_question: '超市一共运来多少瓶牛奶',
    distractors: ['昨天卖掉了10瓶牛奶'],
    question_distractors: ['昨天卖了几瓶', '现在还剩多少瓶'],
    answer: 56,
  },
  {
    grade: '2-down', difficulty: 2,
    content: '有54个座位，隔壁教室有60个座位。已经坐了36人，又来了9人。还有多少个空座位？',
    math_infos: ['有54个座位', '已经坐了36人', '又来了9人'],
    math_question: '还有多少个空座位',
    distractors: ['隔壁教室有60个座位'],
    question_distractors: ['隔壁教室有几个座位', '一共来了多少人'],
    answer: 9,
  },
  {
    grade: '2-down', difficulty: 1,
    content: '一筐鸡蛋有42个，做蛋糕还需要2斤面粉。拿出来6个鸡蛋做蛋糕。筐里还有多少个鸡蛋？',
    math_infos: ['一筐鸡蛋有42个', '拿出来6个鸡蛋'],
    math_question: '筐里还有多少个鸡蛋',
    distractors: ['做蛋糕还需要2斤面粉'],
    question_distractors: ['做蛋糕需要几斤面粉', '做蛋糕一共用了多少材料'],
    answer: 36,
  },
  {
    grade: '2-down', difficulty: 2,
    content: '爸爸有100元，妈妈给了爸爸50元。买了一本35元的书和一支8元的笔。爸爸还剩多少元？',
    math_infos: ['爸爸有100元', '书35元', '笔8元'],
    math_question: '爸爸还剩多少元',
    distractors: ['妈妈给了爸爸50元'],
    question_distractors: ['妈妈给了多少元', '买东西一共花了多少元'],
    answer: 57,
  },
  {
    grade: '2-down', difficulty: 2,
    content: '一列火车有6节车厢，每节可以坐8人。已经上来了20个乘客。这列火车一共可以坐多少人？',
    math_infos: ['有6节车厢', '每节可以坐8人'],
    math_question: '一共可以坐多少人',
    distractors: ['已经上来了20个乘客'],
    question_distractors: ['上来了几个乘客', '还能坐多少人'],
    answer: 48,
  },
  {
    grade: '2-down', difficulty: 1,
    content: '小花有81颗弹珠，小明有50颗弹珠。小花平均分给3个好朋友。每人分到多少颗弹珠？',
    math_infos: ['有81颗弹珠', '平均分给3个好朋友'],
    math_question: '每人分到多少颗弹珠',
    distractors: ['小明有50颗弹珠'],
    question_distractors: ['小明有几颗弹珠', '他们一共有多少颗弹珠'],
    answer: 27,
  },
  {
    grade: '2-down', difficulty: 2,
    content: '篮子里有19个苹果和5个梨，桌上还有3个香蕉。拿走了7个苹果。篮子里还有多少个苹果？',
    math_infos: ['篮子里有19个苹果', '拿走了7个苹果'],
    math_question: '篮子里还有多少个苹果',
    distractors: ['有5个梨', '桌上还有3个香蕉'],
    question_distractors: ['篮子里有几个梨', '一共有多少个水果'],
    answer: 12,
  },
];

async function initDB() {
  const conn = await mysql.createConnection({
    host: config.db.host,
    port: config.db.port,
    user: config.db.user,
    password: config.db.password,
    multipleStatements: true,
  });

  console.log('Creating database...');
  await conn.query(`CREATE DATABASE IF NOT EXISTS ${config.db.database} CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci`);
  await conn.query(`USE ${config.db.database}`);

  console.log('Creating tables...');
  await conn.query(TABLES_SQL);

  console.log('Seeding reading questions...');
  await conn.query('DELETE FROM reading_question');
  for (const q of SEED_QUESTIONS) {
    await conn.query(
      'INSERT INTO reading_question (grade, difficulty, content, math_infos, math_question, distractors, question_distractors, answer) VALUES (?, ?, ?, ?, ?, ?, ?, ?)',
      [q.grade, q.difficulty, q.content, JSON.stringify(q.math_infos), q.math_question, JSON.stringify(q.distractors), JSON.stringify(q.question_distractors), q.answer]
    );
  }

  console.log('Database initialized successfully!');
  await conn.end();
  process.exit(0);
}

initDB().catch(err => {
  console.error('Failed to initialize database:', err);
  process.exit(1);
});
